famliy = []
famliy.append("dad")
famliy.append("momma1")
famliy.append("momma2")
famliy.append("momma3")
famliy.append("momma4")
famliy.append("momma5")
famliy.append("momma6")
famliy.append("momma7")
famliy.append("momma8")
famliy.append("momma9")
print (famliy)
print ("0--> " + famliy[0])
print ("1--> " + famliy[1])
print ("1:3 " + str (famliy[1:3]))
print ("1:5 " + str (famliy[2:5]))
print ("1:? " + str (famliy[1:]))